version: '3.8'

services:
  gotenberg:
    image: thecodingmachine/gotenberg:6
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2g"
    environment:
      - Gotenberg_LOG_LEVEL=debug
    networks:
      - gotenberg_network

networks:
  gotenberg_network:
    driver: bridge
